<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2015.1.2.344
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Отправка Форма Покупка и доставка товаров из Санкт-Петербурга',
	'heading' => 'Отправка новой формы',
	'success_redirect' => 'http://www.vezutebe.ru/spasibo_za_zakaz.html',
	'resources' => array(
		'checkbox_checked' => 'Отмечено',
		'checkbox_unchecked' => 'Флажок не установлен',
		'submitted_from' => 'Формы, отправленные с веб-сайта: %s',
		'submitted_by' => 'IP-адрес посетителя: %s',
		'too_many_submissions' => 'Недопустимо высокое количество отправок с этого IP-адреса за последнее время',
		'failed_to_send_email' => 'Не удалось отправить сообщение эл. почты',
		'invalid_reCAPTCHA_private_key' => 'Недействительный закрытый ключ reCAPTCHA.',
		'invalid_field_type' => 'Неизвестный тип поля \'%s\'.',
		'invalid_form_config' => 'Недопустимая конфигурация поля \"%s\".',
		'unknown_method' => 'Неизвестный метод запроса сервера'
	),
	'email' => array(
		'from' => 'in11@be.ru',
		'to' => 'in11@be.ru'
	),
	'fields' => array(
		'custom_U8138' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Имя',
			'required' => false,
			'errors' => array(
			)
		),
		'Email' => array(
			'order' => 3,
			'type' => 'email',
			'label' => 'Электронная почта',
			'required' => false,
			'errors' => array(
				'format' => 'Поле \'Электронная почта\' содержит недействительное сообщение эл. почты.'
			)
		),
		'custom_U8152' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Стоимость товара',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Стоимость товара\' не может быть пустым.'
			)
		),
		'custom_U8161' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Номер телефона',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Номер телефона\' не может быть пустым.'
			)
		),
		'custom_U8170' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Стоимость доставки по Санкт-Петербургу',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U8134' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Ориентировочный вес товара',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Ориентировочный вес товара\' не может быть пустым.'
			)
		),
		'custom_U8143' => array(
			'order' => 9,
			'type' => 'checkbox',
			'label' => 'Товар является опасным для жизни и здоровья человека и окружающей среды/габаритным/скоропортящимся',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U8166' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Ориентировочные габариты (Д*Ш*Всм)',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Ориентировочные габариты (Д*Ш*Всм)\' не может быть пустым.'
			)
		),
		'custom_U8147' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Наименование товара',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Наименование товара\' не может быть пустым.'
			)
		)
	)
);

process_form($form);
?>
